MAX_PACKET_LENGTH = 300

# programmers
AVR_PROGRAMMER_BYTE = 0x00

# Send packet types
ACK_PACKET_BYTE     = 0xAA
USART_PACKET_BYTE   = 0xBB
ERROR_PACKET_BYTE   = 0xEE
MEMORY_PACKET_BYTE  = 0xCC

# Receive packet types
LOG_PACKET_BYTE                 =   0x10
AVR_PROG_INIT_BYTE		=   0x11
STOP_PROGRAMMER_PACKET_BYTE	=   0x22
CMD_PACKET_BYTE		        =   0x33
RESET_PACKET_BYTE		=   0x44
PROG_MEM_PACKET_BYTE		=   0x55
USART_INIT_PACKET_BYTE		=   0x66
LOAD_MCU_INFO_BYTE		=   0x77
READ_MEM_PACKET_BYTE		=   0x88
PGM_ENABLE_PACKET_BYTE		=   0x99
LOAD_NETWORK_INFO_BYTE		=   0x12
NETWORK_INFO_LOADED_BYTE	=   0x13
NONE_PACKET_BYTE 		=   0x00

INTERNAL_ERROR_BYTE	 =  0x00
WRONG_PACKET_BYTE	 =  0x01

# Header structure
SIZE_FIELD_OFFSET	    =   0
SIZE_FIELD_SIZE		    =   2
TYPE_FIELD_OFFSET	    =   (SIZE_FIELD_OFFSET + SIZE_FIELD_SIZE)
TYPE_FIELD_SIZE		    =   1
CRC_FIELD_SIZE     	    =   4
PACKET_HEADER_SIZE	    =   (SIZE_FIELD_SIZE + TYPE_FIELD_SIZE)
PACKET_RESERVED_BYTES	=   (SIZE_FIELD_SIZE + TYPE_FIELD_SIZE + CRC_FIELD_SIZE)

# Reset packet structure
RESET_BYTE_OFFSET	=   0
RESET_ENABLE 		=   1
RESET_DISABLE		=   0

# USART Packet structure
USART_PACKET_DATA_SIZE          =   4
USART_BAUDRATE_BYTE_OFFSET      =   (0)
USART_PARITY_BYTE_OFFSET    	=   (USART_BAUDRATE_BYTE_OFFSET+1)
USART_DATA_BITS_BYTE_OFFSET 	=   (USART_PARITY_BYTE_OFFSET+1)
USART_STOP_BITS_BYTE_OFFSET 	=   (USART_DATA_BITS_BYTE_OFFSET+1)

# USART Config bytes
USART_PARITY_EVEN	    =   0xC0
USART_PARITY_ODD	    =   0xC1
USART_PARITY_NONE	    =   0xC2
USART_DATA_BITS_8	    =   0xC3
USART_DATA_BITS_9	    =   0xC4
USART_STOP_BITS_1	    =   0xC5
USART_STOP_BITS_2	    =   0xC6
USART_BAUDRATE_9600         =   0xC7
USART_BAUDRATE_19200	    =   0xC8
USART_BAUDRATE_38400        =   0xC9
USART_BAUDRATE_57600	    =   0xCA
USART_BAUDRATE_74880        =   0xCB
USART_BAUDRATE_115200	    =   0xCD

BAUDRATE_9600   = 9600
BAUDRATE_19200  = 19200
BAUDRATE_38400  = 38400
BAUDRATE_57600  = 57600
BAUDRATE_74880  = 74880
BAUDRATE_115200 = 115200


# USART errors
USART_PARITY_ERROR_BYTE 	=   0xE0
USART_FRAME_ERROR_BYTE		=   0xE1
USART_DATA_BITS_ERROR_BYTE	=   0xE2
USART_STOP_BITS_ERROR_BYTE	=   0xE3
USART_BAUDRATE_ERROR_BYTE	=   0xE4


# 10 ms
PACKET_WAIT_TIMEOUT = 3
ACK_WAIT_TIMEOUT    = 2

# Updating esp network info
PACKET_NETWORK_INFO_BYTE = 0x12
